name: os
version: 0.1.1
description:
  Access to operating system APIs (using 'dart:ffi'). Virtual memory management, IPC pipes, file
  permissions, etc.
homepage: https://github.com/terrier989/os
author: terrier989 <terrier989@gmail.com>

environment:
  sdk: '>=2.5.0-dev.2.1 <3.0.0'

dependencies:
  ffi: ^0.1.1
  meta: ^1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0